encoding: utf-8

# SEO相关信息
title: 瓜娃子大叔 Blog
description: 瓜娃子大叔的个人博客
keywords: 瓜娃子,禁书,稀缺,成人电影,中国,特色,政治
author: 瓜娃子大叔
footerText: 'Copyright © 2020 港ICP12138备'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: '' #'http://guawazidashu.me'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/139146 # 瓜娃子微信注册https://txc.qq.com/

# 菜单
menu:
  - title: 最新
    url: /
  - title: 分类
    url: /pages/categories.html
  - title: 查询
    url: /pages/search.html
  # - title: 友链
  #   url: /pages/links.html
  - title: 关于
    url: /pages/about.html
  - title: 留言
    url: /pages/chat.html


# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 今日头条
    url: https://profile.zjurl.cn/rogue/ugc/profile/?version_code=7.6.3&version_name=70603&user_id=72878533118&media_id=1596868651166723&request_source=1&active_tab=dongtai&device_id=65&app_name=news_article
